name: 🐳 Docker Build & Push QA Images
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        description: 'Optional version tag for the Docker image. If not provided, will use branch name or commit SHA'
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  docker-build-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build QA images
        run: |
            docker build -t muaazbayat01/qa-sdproject-backend -f backend/backend.Dockerfile backend/.
            docker build -t muaazbayat01/qa-sdproject-frontend -f frontend/frontend.Dockerfile frontend/.  
      - name: Push QA images
        run: |
            docker push muaazbayat01/qa-sdproject-frontend
            docker push muaazbayat01/qa-sdproject-backend
