name: Backend Tests (Reusable)

on:
  workflow_call:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Run Backend Tests
        working-directory: backend
        env:
          DATABASE_URL: postgresql://neondb_owner:npg_ZUgQeMX64rTm@ep-dry-term-a8pxk2za-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
          CLERK_SECRET_KEY: 'sk_test_Lo9YZO4TWhU0veJ5K5L71oYYLJM8nrVNrOo2QhWHv8' 
          AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=sdprojectimages2;AccountKey=qHRtSO+ps2HhYxj7rkxVWPEzhrLdp7COvSKWEniDcrSggTbFeg3iiNJyQyA6+jtbEK6NSy3zifYE+ASthH7ztQ==;EndpointSuffix=core.windows.net"
          AZURE_CONTAINER: 'product-images' 
          STITCH_CLIENT_KEY: test-bfd0ab2c-0258-4973-8f4c-06e0e0ad97a3
          STITCH_CLIENT_SECRET: PQZn85k9I2P2DqbhifL0h3C0VhLLJhaXWimS6JAmqGWw3AixZ54f0nR1reGL6J/2
        run: npm test
        
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: backend/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
